### ISSUE TITLE
Update the SSH keys part

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/git-novice-branch-pr#37]
Need to add in the SSH part from the swc/git-novice lesson.

I recommend we move it to the setup/config episode.

**Comment by sstevens2** [comment]
Also needs to be fixed in the clone part of the PR episode

**Comment by srappel** [comment]
I made [PR 42](https://github.com/carpentries-incubator/git-novice-branch-pr/pull/42) before I saw this issue. My PR would put it in the GitHub episode instead of in the setup. 

I'm hesitant to put it in setup, because there's just so many steps.

I might teach my workshop from my fork and see how it goes.

**Comment by sstevens2** [comment]
I've seen it done in the github episode and it was a bit of a struggle.  The workshop was running out of time and in that part of the lesson it was a lot to deal with this ssh step in addition to setting up the github repo and learning to push and pull.  So I switched it up and taught it in the setup section myself. It does make the setup a bit long but it is hard to put it in right before the github stuff as that is a lot of cognitive load and setup as well.

**Comment by srappel** [comment]
[PR 42](https://github.com/carpentries-incubator/git-novice-branch-pr/pull/42) ready for review.
